Handle ENAMETOOLONG on Linux (#1940)
giampaolo/psutil pull request #1955
Opened 2021-06-02 11:12 UTC by nradchenko

## Summary

* OS: Linux
* Bug fix: yes
* Type: core
* Fixes: #1940

## Description

This fixes the bug described in #1940 (handling ENAMETOOLONG when resolving broken fd symlinks in procfs)

2021-10-02 09:50 UTC, giampaolo requested changes
Sorry for the late reviews. I added some inline comments.

2021-10-02 09:50 UTC, giampaolo commented on psutil/tests/test_linux.py
> +    def test_open_files_fd_broken(self):
Can you rename this to `test_open_files_enametoolong`?

2021-10-02 09:50 UTC, giampaolo commented on psutil/tests/test_linux.py
> +                assert m.called
It looks like in here you mock `Connections` class but you're testing `Process.open_files()` instead of `Process.connections()`.

2021-10-05 18:13 UTC, merged

2021-10-08 15:35 UTC, nradchenko commented
Sorry @giampaolo , I'm a bit late too :smile: Thanks for the feedback and post-merge fixes :+1: