Build musllinux wheels
giampaolo/psutil pull request #2126
Opened 2022-07-30 23:18 UTC by ben9923

## Summary

* OS: Linux (musl)
* Bug fix: no
* Type: wheels

## Description

Added `musllinux` wheel support to CI. Installing fully-featured variants of common commands, compared to their `busybox` variants (namely `ps`, `df`) was the only thing necessary for tests to pass.
Should be useful for Alpine Linux users, which probably make a not-too-little percentage of the Linux users (Was ~1% back in 2017, I expect it to be much higher now).

No link for an issue as apparently there is none for musl/Alpine wheels 😛

I saw some ongoing efforts to refactor CI w/ Arm support, etc. so in case this one is merged before those PRs, someone should make sure they don't break musl wheels build.
BTW - In case `cibuildwheel` configuration becomes toml-based, an 'override' for musllinux may be used instead of the hacky `command -v` check here.

2022-09-09 11:48 UTC, ben9923 commented
@giampaolo Rebased to show changes as part of `5.9.3`.
Shouldn't #2037 appear there too? It currently shows up as part of `5.9.1`.

Apparently `psutil.tests.test_linux.TestSystemNetIfStats.test_flags` is failing on `master` so checks are not passing, but you can see the previous run [succeeded](https://github.com/giampaolo/psutil/actions/runs/2985493105) :)

2022-09-15 18:38 UTC, ben9923 commented
@giampaolo Added a fix for `master` Python 2 fails (which also affect `Alpine`) + now those `ifconfig` tests run for Python 3 (previously skipped) :)

BTW, `net-tools` ifconfig statistics are somewhat broken under `musl`... They use non-standard format strings that break `/proc/net/dev` parsing with musl. The alpine package also doesn't seem to override the busybox variant.
I just gave up on installing it under `Alpine` and let it behave like the old version in the Python 2 image.

`freebsd` appears to fail on something completely unrelated, I guess there was some sort of remote package update that makes it fail.

2022-10-21 13:08 UTC, ben9923 commented
@giampaolo Adapted for pyproject.toml-based changes.

Please consider merging those changes :)
I don't think they make the package harder to maintain/release, and pretty much align with every other major Python package that now ships musllinux wheels.
Thanks for the effort in merging macOS arm64 and abi3!

2023-04-17 14:50 UTC, MrMino commented
@giampaolo is there anything else needed for this to go through? This would speed up lots of CI runs and let us remove `psutil` build dependencies from our containers.

2023-05-27 12:17 UTC, Sodki commented
`psutil` is a dependency of many projects, not having a wheel for `musllinux` breaks a lot of pipelines unnecessarily.

2023-07-26 13:05 UTC, MrMino commented
For the record, the musllinux build skip comes from #2024, namely [this commit](https://github.com/giampaolo/psutil/pull/2024/commits/62c9b6a19bb7ebf9f59cbb38c11afbb0df27ad0a) made by @giampaolo. It then got moved into `pyproject.toml` in 3f81c62ecb37098318fd1f80eebb0bdffc8f097c.

It looks like the patch was made in order to fix build failures. Since @ben9923 changes seem to result in `cibuildwheel` [correctly building the wheels](https://github.com/giampaolo/psutil/actions/runs/5356360270/job/14501655305#step:5:12710), there doesn't seem to be any apparent reason not to accept this.

@giampaolo are we missing something? Sorry for spamming, but this is a serious pain point for me and many others, since we cannot test `psutil`-dependant code on Alpine without modifying our Docker images, and it looks like the fix is just one click away.

2023-10-16 12:27 UTC, MrMino commented
@giampaolo kind nudge. This has little to no overhead and would greatly improve the usage of `psutil` in containers.

2023-10-24 00:02 UTC, sgrtye commented
@giampaolo This change is essential for Alpine-based images. A small image size is a top priority for Alpine users, and these improvements will make psutil more compatible and efficient in Python-Alpine environments. Let's streamline this process and bring the benefits of psutil to a wider audience in Alpine containers. 🐧✨

2023-11-30 12:11 UTC, MrMino commented
I suppose the request would be more persuasive if we fixed the build failures.

@ben9923 can you confirm with any degree of certainty that these do not stem from your changes?

2023-12-22 17:33 UTC, ben9923 commented
#2326 contained the build tools installation instructions from this PR and was merged to `master`. Rebased to fix conflicts :)

2025-09-19 07:07 UTC, kiskele requested changes

2025-09-19 07:07 UTC, kiskele commented on pyproject.toml
> +before-all = "apk --no-cache add coreutils procps"
python/pip shall be run without root privileges. It would be better to choose a proper docker image for running the build tools

2025-09-20 15:41 UTC, ben9923 commented on pyproject.toml
> +before-all = "apk --no-cache add coreutils procps"
You may propose such a change to `cibuildwheel` devs.

2025-09-24 03:22 UTC, ben9923 commented
#2425, #2448 added test deps for glibc & musl, rebased (with a little fix for the `apk` command) :)
This PR was slowly stripped out of content over those years, now all it has left is the musllinux skip removal 😉 

@giampaolo Given the Python 2.7 drop, would musl wheels be easier to maintain now?

BTW - noticed only 3.13 tests are being run, 3.8 aren't (seems like an oversight in fb75b28?)

2026-01-21 20:45 UTC, MrMino commented
@giampaolo I believe this has been implemented in https://github.com/giampaolo/psutil/pull/2690 and can be closed

2026-01-21 20:51 UTC, closed without merging