Drop python 3.4 & 3.5
giampaolo/psutil pull request #2246
Opened 2023-04-22 11:35 UTC by mayeut

## Summary

* OS: all
* Bug fix: no
* Type: core

## Description

Python 3.4 & 3.5 are currently untested in CI (c.f. https://github.com/giampaolo/psutil/pull/2162 & https://github.com/giampaolo/psutil/pull/2102#issuecomment-1284617987)

Given the download count for last week below, I propose to just drop support for those versions.

```
psutil % pypinfo -l 25 --percent -sd -8 'psutil==5.9.*' pyversion
Served from cache: False
Data processed: 691.93 MiB
Data billed: 692.00 MiB
Estimated cost: $0.01

| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 3.8            |  38.26% |      5,134,737 |
| 3.7            |  31.19% |      4,186,332 |
| 3.9            |  10.86% |      1,456,900 |
| 3.10           |   9.75% |      1,309,074 |
| 3.6            |   6.60% |        885,766 |
| 3.11           |   2.22% |        298,476 |
| 2.7            |   1.05% |        140,466 |
| 3.5            |   0.06% |          7,460 |
| 3.12           |   0.01% |            688 |
| 3.4            |   0.00% |            371 |
| Total          |         |     13,420,270 |
```

2023-04-22 13:47 UTC, giampaolo commented
Mmm. This should be part of a major release. Let's merge this for psutil 6.0.0, where I will also introduce some other (not serious) incompatibilities.

2023-04-23 10:37 UTC, mayeut commented
IMHO, it could also be part of a minor version bump like it was when dropping 2.6. Obviously it depends on the plans you have for minor vs major release.
If you have plans for a 6.0, it might be time to consider dropping 2.7 ?
It still has many downloads but python 2.7 has now been EOL for more than 3 years. It might also depend on what kind of commitment you have w.r.t. Tidelift support ?

2023-07-31 04:02 UTC, giampaolo commented
Let's take the chance to break compatibility also in some other aspects (more later). Could you please bump up the version to 5.7.0 and also update the doc in the section related to platforms history support? (I am traveling now so I cannot search it; it's near the end of the doc)

Thanks Matthieu

2023-07-31 04:27 UTC, giampaolo requested changes

2023-07-31 04:27 UTC, giampaolo commented on psutil/_psposix.py
> +if sys.version_info[0] >= 3:
Please use PY3 constant instead.

2023-07-31 04:27 UTC, giampaolo commented on psutil/_pslinux.py
> +if sys.version_info[0] >= 3:
Please use PY3 constant instead.

2023-07-31 04:27 UTC, giampaolo commented on psutil/_pswindows.py
> +if sys.version_info[0] >= 3:
Please use PY3 constant instead.

2023-07-31 04:27 UTC, giampaolo commented on psutil/tests/__init__.py
> +if sys.version_info[0] >= 3:
Please use PY3 constant instead.

2023-07-31 04:27 UTC, giampaolo commented on psutil/tests/test_contracts.py
> +            if sys.version_info[0] >= 3:
Please use PY3 constant instead.

2023-07-31 04:27 UTC, giampaolo commented on psutil/tests/test_system.py
> +                if sys.version_info[0] >= 3 and not PYPY:
Ditto.

2023-08-01 01:17 UTC, merged